In [3]:
import pandas as pd

df=pd.read_csv(
    "data/Perovskite_database_content_all_data.csv", low_memory=False 
)
print(df.shape)

(42443, 410)

In [4]:
display(df.head())

,Ref_ID,Ref_ID_temp,Ref_name_of_person_entering_the_data,Ref_data_entered_by_author,Ref_DOI_number,Ref_lead_author,Ref_publication_date,Ref_journal,Ref_part_of_initial_dataset,Ref_original_filename_data_upload,...,Outdoor_PCE_Tse80,Outdoor_PCE_after_1000_h,Outdoor_power_generated,Outdoor_link_raw_data_for_outdoor_trace,Outdoor_detaild_weather_data_available,Outdoor_link_detailed_weather_data,Outdoor_spectral_data_available,Outdoor_link_spectral_data,Outdoor_irradiance_measured,Outdoor_link_irradiance_data
0,1,1,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,2015-01-06,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN
1,2,2,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,2015-01-06,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN
2,3,3,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,2015-01-06,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN
3,4,4,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,2015-01-06,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN
4,5,5,Adam Hultqvist,False,10.1021/jp5126624,Sabba et al.,2015-01-06,The Journal of Physical Chemistry C,True,Historic dataset on 2020 11 22_v7.xlsx,...,NaN,NaN,NaN,NaN,False,NaN,False,NaN,False,NaN

In [6]:
print(df.columns.tolist())

['Ref_ID', 'Ref_ID_temp', 'Ref_name_of_person_entering_the_data', 'Ref_data_entered_by_author', 'Ref_DOI_number', 'Ref_lead_author', 'Ref_publication_date', 'Ref_journal', 'Ref_part_of_initial_dataset', 'Ref_original_filename_data_upload', 'Ref_free_text_comment', 'Ref_internal_sample_id', 'Cell_stack_sequence', 'Cell_area_total', 'Cell_area_measured', 'Cell_number_of_cells_per_substrate', 'Cell_architecture', 'Cell_flexible', 'Cell_flexible_min_bending_radius', 'Cell_semitransparent', 'Cell_semitransparent_AVT', 'Cell_semitransparent_wavelength_range', 'Cell_semitransparent_raw_data', 'Module', 'Module_number_of_cells_in_module', 'Module_area_total', 'Module_area_effective', 'Module_JV_data_recalculated_per_cell', 'Substrate_stack_sequence', 'Substrate_thickness', 'Substrate_area', 'Substrate_supplier', 'Substrate_brand_name', 'Substrate_deposition_procedure', 'Substrate_surface_roughness_rms', 'Substrate_etching_procedure', 'Substrate_cleaning_procedure', 'ETL_stack_sequence', 'ETL_thickness', 'ETL_additives_compounds', 'ETL_additives_concentrations', 'ETL_deposition_procedure', 'ETL_deposition_aggregation_state_of_reactants', 'ETL_deposition_synthesis_atmosphere', 'ETL_deposition_synthesis_atmosphere_pressure_total', 'ETL_deposition_synthesis_atmosphere_pressure_partial', 'ETL_deposition_synthesis_atmosphere_relative_humidity', 'ETL_deposition_solvents', 'ETL_deposition_solvents_mixing_ratios', 'ETL_deposition_solvents_supplier', 'ETL_deposition_solvents_purity', 'ETL_deposition_reaction_solutions_compounds', 'ETL_deposition_reaction_solutions_compounds_supplier', 'ETL_deposition_reaction_solutions_compounds_purity', 'ETL_deposition_reaction_solutions_concentrations', 'ETL_deposition_reaction_solutions_volumes', 'ETL_deposition_reaction_solutions_age', 'ETL_deposition_reaction_solutions_temperature', 'ETL_deposition_substrate_temperature', 'ETL_deposition_thermal_annealing_temperature', 'ETL_deposition_thermal_annealing_time', 'ETL_deposition_thermal_annealing_atmosphere', 'ETL_storage_time_until_next_deposition_step', 'ETL_storage_atmosphere', 'ETL_storage_relative_humidity', 'ETL_surface_treatment_before_next_deposition_step', 'Perovskite_single_crystal', 'Perovskite_dimension_0D', 'Perovskite_dimension_2D', 'Perovskite_dimension_2D3D_mixture', 'Perovskite_dimension_3D', 'Perovskite_dimension_3D_with_2D_capping_layer', 'Perovskite_dimension_list_of_layers', 'Perovskite_composition_perovskite_ABC3_structure', 'Perovskite_composition_perovskite_inspired_structure', 'Perovskite_composition_a_ions', 'Perovskite_composition_a_ions_coefficients', 'Perovskite_composition_b_ions', 'Perovskite_composition_b_ions_coefficients', 'Perovskite_composition_c_ions', 'Perovskite_composition_c_ions_coefficients', 'Perovskite_composition_none_stoichiometry_components_in_excess', 'Perovskite_composition_short_form', 'Perovskite_composition_long_form', 'Perovskite_composition_assumption', 'Perovskite_composition_inorganic', 'Perovskite_composition_leadfree', 'Perovskite_additives_compounds', 'Perovskite_additives_concentrations', 'Perovskite_thickness', 'Perovskite_band_gap', 'Perovskite_band_gap_graded', 'Perovskite_band_gap_estimation_basis', 'Perovskite_pl_max', 'Perovskite_deposition_number_of_deposition_steps', 'Perovskite_deposition_procedure', 'Perovskite_deposition_aggregation_state_of_reactants', 'Perovskite_deposition_synthesis_atmosphere', 'Perovskite_deposition_synthesis_atmosphere_pressure_total', 'Perovskite_deposition_synthesis_atmosphere_pressure_partial', 'Perovskite_deposition_synthesis_atmosphere_relative_humidity', 'Perovskite_deposition_solvents', 'Perovskite_deposition_solvents_mixing_ratios', 'Perovskite_deposition_solvents_supplier', 'Perovskite_deposition_solvents_purity', 'Perovskite_deposition_reaction_solutions_compounds', 'Perovskite_deposition_reaction_solutions_compounds_supplier', 'Perovskite_deposition_reaction_solutions_compounds_purity', 'Perovskite_deposition_reaction_solutions_concentrations', 'Perovskite_deposition_reaction_solutions_volumes', 'Perovskite_deposition_reaction_solutions_age', 'Perovskite_deposition_reaction_solutions_temperature', 'Perovskite_deposition_substrate_temperature', 'Perovskite_deposition_quenching_induced_crystallisation', 'Perovskite_deposition_quenching_media', 'Perovskite_deposition_quenching_media_mixing_ratios', 'Perovskite_deposition_quenching_media_volume', 'Perovskite_deposition_quenching_media_additives_compounds', 'Perovskite_deposition_quenching_media_additives_concentrations', 'Perovskite_deposition_thermal_annealing_temperature', 'Perovskite_deposition_thermal_annealing_time', 'Perovskite_deposition_thermal_annealing_atmosphere', 'Perovskite_deposition_thermal_annealing_relative_humidity', 'Perovskite_deposition_thermal_annealing_pressure', 'Perovskite_deposition_solvent_annealing', 'Perovskite_deposition_solvent_annealing_timing', 'Perovskite_deposition_solvent_annealing_solvent_atmosphere', 'Perovskite_deposition_solvent_annealing_time', 'Perovskite_deposition_solvent_annealing_temperature', 'Perovskite_deposition_after_treatment_of_formed_perovskite', 'Perovskite_deposition_after_treatment_of_formed_perovskite_met', 'Perovskite_storage_time_until_next_deposition_step', 'Perovskite_storage_atmosphere', 'Perovskite_storage_relative_humidity', 'Perovskite_surface_treatment_before_next_deposition_step', 'HTL_stack_sequence', 'HTL_thickness_list', 'HTL_additives_compounds', 'HTL_additives_concentrations', 'HTL_deposition_procedure', 'HTL_deposition_aggregation_state_of_reactants', 'HTL_deposition_synthesis_atmosphere', 'HTL_deposition_synthesis_atmosphere_pressure_total', 'HTL_deposition_synthesis_atmosphere_pressure_partial', 'HTL_deposition_synthesis_atmosphere_relative_humidity', 'HTL_deposition_solvents', 'HTL_deposition_solvents_mixing_ratios', 'HTL_deposition_solvents_supplier', 'HTL_deposition_solvents_purity', 'HTL_deposition_reaction_solutions_compounds', 'HTL_deposition_reaction_solutions_compounds_supplier', 'HTL_deposition_reaction_solutions_compounds_purity', 'HTL_deposition_reaction_solutions_concentrations', 'HTL_deposition_reaction_solutions_volumes', 'HTL_deposition_reaction_solutions_age', 'HTL_deposition_reaction_solutions_temperature', 'HTL_deposition_substrate_temperature', 'HTL_deposition_thermal_annealing_temperature', 'HTL_deposition_thermal_annealing_time', 'HTL_deposition_thermal_annealing_atmosphere', 'HTL_storage_time_until_next_deposition_step', 'HTL_storage_atmosphere', 'HTL_storage_relative_humidity', 'HTL_surface_treatment_before_next_deposition_step', 'Backcontact_stack_sequence', 'Backcontact_thickness_list', 'Backcontact_additives_compounds', 'Backcontact_additives_concentrations', 'Backcontact_deposition_procedure', 'Backcontact_deposition_aggregation_state_of_reactants', 'Backcontact_deposition_synthesis_atmosphere', 'Backcontact_deposition_synthesis_atmosphere_pressure_total', 'Backcontact_deposition_synthesis_atmosphere_pressure_partial', 'Backcontact_deposition_synthesis_atmosphere_relative_humidity', 'Backcontact_deposition_solvents', 'Backcontact_deposition_solvents_mixing_ratios', 'Backcontact_deposition_solvents_supplier', 'Backcontact_deposition_solvents_purity', 'Backcontact_deposition_reaction_solutions_compounds', 'Backcontact_deposition_reaction_solutions_compounds_supplier', 'Backcontact_deposition_reaction_solutions_compounds_purity', 'Backcontact_deposition_reaction_solutions_concentrations', 'Backcontact_deposition_reaction_solutions_volumes', 'Backcontact_deposition_reaction_solutions_age', 'Backcontact_deposition_reaction_solutions_temperature', 'Backcontact_deposition_substrate_temperature', 'Backcontact_deposition_thermal_annealing_temperature', 'Backcontact_deposition_thermal_annealing_time', 'Backcontact_deposition_thermal_annealing_atmosphere', 'Backcontact_storage_time_until_next_deposition_step', 'Backcontact_storage_atmosphere', 'Backcontact_storage_relative_humidity', 'Backcontact_surface_treatment_before_next_deposition_step', 'Add_lay_front', 'Add_lay_front_function', 'Add_lay_front_stack_sequence', 'Add_lay_front_thickness_list', 'Add_lay_front_additives_compounds', 'Add_lay_front_additives_concentrations', 'Add_lay_front_deposition_procedure', 'Add_lay_front_deposition_aggregation_state_of_reactants', 'Add_lay_front_deposition_synthesis_atmosphere', 'Add_lay_front_deposition_synthesis_atmosphere_pressure_total', 'Add_lay_front_deposition_synthesis_atmosphere_pressure_partial', 'Add_lay_front_deposition_synthesis_atmosphere_relative_humidity', 'Add_lay_front_deposition_solvents', 'Add_lay_front_deposition_solvents_mixing_ratios', 'Add_lay_front_deposition_solvents_supplier', 'Add_lay_front_deposition_solvents_purity', 'Add_lay_front_deposition_reaction_solutions_compounds', 'Add_lay_front_deposition_reaction_solutions_compounds_supplier', 'Add_lay_front_deposition_reaction_solutions_compounds_purity', 'Add_lay_front_deposition_reaction_solutions_concentrations', 'Add_lay_front_deposition_reaction_solutions_volumes', 'Add_lay_front_deposition_reaction_solutions_age', 'Add_lay_front_deposition_reaction_solutions_temperature', 'Add_lay_front_deposition_substrate_temperature', 'Add_lay_front_deposition_thermal_annealing_temperature', 'Add_lay_front_deposition_thermal_annealing_time', 'Add_lay_front_deposition_thermal_annealing_atmosphere', 'Add_lay_front_storage_time_until_next_deposition_step', 'Add_lay_front_storage_atmosphere', 'Add_lay_front_storage_relative_humidity', 'Add_lay_front_surface_treatment_before_next_deposition_step', 'Add_lay_back', 'Add_lay_back_function', 'Add_lay_back_stack_sequence', 'Add_lay_back_thickness_list', 'Add_lay_back_additives_compounds', 'Add_lay_back_additives_concentrations', 'Add_lay_back_deposition_procedure', 'Add_lay_back_deposition_aggregation_state_of_reactants', 'Add_lay_back_deposition_synthesis_atmosphere', 'Add_lay_back_deposition_synthesis_atmosphere_pressure_total', 'Add_lay_back_deposition_synthesis_atmosphere_pressure_partial', 'Add_lay_back_deposition_synthesis_atmosphere_relative_humidity', 'Add_lay_back_deposition_solvents', 'Add_lay_back_deposition_solvents_mixing_ratios', 'Add_lay_back_deposition_solvents_supplier', 'Add_lay_back_deposition_solvents_purity', 'Add_lay_back_deposition_reaction_solutions_compounds', 'Add_lay_back_deposition_reaction_solutions_compounds_supplier', 'Add_lay_back_deposition_reaction_solutions_compounds_purity', 'Add_lay_back_deposition_reaction_solutions_concentrations', 'Add_lay_back_deposition_reaction_solutions_volumes', 'Add_lay_back_deposition_reaction_solutions_age', 'Add_lay_back_deposition_reaction_solutions_temperature', 'Add_lay_back_deposition_substrate_temperature', 'Add_lay_back_deposition_thermal_annealing_temperature', 'Add_lay_back_deposition_thermal_annealing_time', 'Add_lay_back_deposition_thermal_annealing_atmosphere', 'Add_lay_back_storage_time_until_next_deposition_step', 'Add_lay_back_storage_atmosphere', 'Add_lay_back_storage_relative_humidity', 'Add_lay_back_surface_treatment_before_next_deposition_step', 'Encapsulation', 'Encapsulation_stack_sequence', 'Encapsulation_edge_sealing_materials', 'Encapsulation_atmosphere_for_encapsulation', 'Encapsulation_water_vapour_transmission_rate', 'Encapsulation_oxygen_transmission_rate', 'JV_measured', 'JV_average_over_n_number_of_cells', 'JV_certified_values', 'JV_certification_institute', 'JV_storage_age_of_cell', 'JV_storage_atmosphere', 'JV_storage_relative_humidity', 'JV_test_atmosphere', 'JV_test_relative_humidity', 'JV_test_temperature', 'JV_light_source_type', 'JV_light_source_brand_name', 'JV_light_source_simulator_class', 'JV_light_intensity', 'JV_light_spectra', 'JV_light_wavelength_range', 'JV_light_illumination_direction', 'JV_light_masked_cell', 'JV_light_mask_area', 'JV_scan_speed', 'JV_scan_delay_time', 'JV_scan_integration_time', 'JV_scan_voltage_step', 'JV_preconditioning_protocol', 'JV_preconditioning_time', 'JV_preconditioning_potential', 'JV_preconditioning_light_intensity', 'JV_reverse_scan_Voc', 'JV_reverse_scan_Jsc', 'JV_reverse_scan_FF', 'JV_reverse_scan_PCE', 'JV_reverse_scan_Vmp', 'JV_reverse_scan_Jmp', 'JV_reverse_scan_series_resistance', 'JV_reverse_scan_shunt_resistance', 'JV_forward_scan_Voc', 'JV_forward_scan_Jsc', 'JV_forward_scan_FF', 'JV_forward_scan_PCE', 'JV_forward_scan_Vmp', 'JV_forward_scan_Jmp', 'JV_forward_scan_series_resistance', 'JV_forward_scan_shunt_resistance', 'JV_link_raw_data', 'JV_default_Voc', 'JV_default_Jsc', 'JV_default_FF', 'JV_default_PCE', 'JV_default_Voc_scan_direction', 'JV_default_Jsc_scan_direction', 'JV_default_FF_scan_direction', 'JV_default_PCE_scan_direction', 'JV_hysteresis_index', 'Stabilised_performance_measured', 'Stabilised_performance_procedure', 'Stabilised_performance_procedure_metrics', 'Stabilised_performance_measurement_time', 'Stabilised_performance_PCE', 'Stabilised_performance_Vmp', 'Stabilised_performance_Jmp', 'Stabilised_performance_link_raw_data', 'EQE_measured', 'EQE_light_bias', 'EQE_integrated_Jsc', 'EQE_link_raw_data', 'Stability_measured', 'Stability_protocol', 'Stability_average_over_n_number_of_cells', 'Stability_light_source_type', 'Stability_light_source_brand_name', 'Stability_light_source_simulator_class', 'Stability_light_intensity', 'Stability_light_spectra', 'Stability_light_wavelength_range', 'Stability_light_illumination_direction', 'Stability_light_load_condition', 'Stability_light_cycling_times', 'Stability_light_UV_filter', 'Stability_potential_bias_load_condition', 'Stability_potential_bias_range', 'Stability_potential_bias_passive_resistance', 'Stability_temperature_load_condition', 'Stability_temperature_range', 'Stability_temperature_cycling_times', 'Stability_temperature_ramp_speed', 'Stability_atmosphere', 'Stability_atmosphere_oxygen_concentration', 'Stability_relative_humidity_load_conditions', 'Stability_relative_humidity_range', 'Stability_relative_humidity_average_value', 'Stability_time_total_exposure', 'Stability_periodic_JV_measurements', 'Stability_periodic_JV_measurements_time_between_jv', 'Stability_PCE_initial_value', 'Stability_PCE_burn_in_observed', 'Stability_PCE_end_of_experiment', 'Stability_PCE_T95', 'Stability_PCE_Ts95', 'Stability_PCE_T80', 'Stability_PCE_Ts80', 'Stability_PCE_Te80', 'Stability_PCE_Tse80', 'Stability_PCE_after_1000_h', 'Stability_lifetime_energy_yield', 'Stability_flexible_cell_number_of_bending_cycles', 'Stability_flexible_cell_bending_radius', 'Stability_flexible_cell_PCE_initial_value', 'Stability_flexible_cell_PCE_end_of_experiment', 'Stability_link_raw_data_for_stability_trace', 'Outdoor_tested', 'Outdoor_protocol', 'Outdoor_average_over_n_number_of_cells', 'Outdoor_location_country', 'Outdoor_location_city', 'Outdoor_location_coordinates', 'Outdoor_location_climate_zone', 'Outdoor_installation_tilt', 'Outdoor_installation_cardinal_direction', 'Outdoor_installation_number_of_solar_tracking_axis', 'Outdoor_time_season', 'Outdoor_time_start', 'Outdoor_time_end', 'Outdoor_time_total_exposure', 'Outdoor_potential_bias_load_condition', 'Outdoor_potential_bias_range', 'Outdoor_potential_bias_passive_resistance', 'Outdoor_temperature_load_condition', 'Outdoor_temperature_range', 'Outdoor_temperature_tmodule', 'Outdoor_periodic_JV_measurements', 'Outdoor_periodic_JV_measurements_time_between_measurements', 'Outdoor_PCE_initial_value', 'Outdoor_PCE_burn_in_observed', 'Outdoor_PCE_end_of_experiment', 'Outdoor_PCE_T95', 'Outdoor_PCE_Ts95', 'Outdoor_PCE_T80', 'Outdoor_PCE_Ts80', 'Outdoor_PCE_Te80', 'Outdoor_PCE_Tse80', 'Outdoor_PCE_after_1000_h', 'Outdoor_power_generated', 'Outdoor_link_raw_data_for_outdoor_trace', 'Outdoor_detaild_weather_data_available', 'Outdoor_link_detailed_weather_data', 'Outdoor_spectral_data_available', 'Outdoor_link_spectral_data', 'Outdoor_irradiance_measured', 'Outdoor_link_irradiance_data']

In [7]:
missing = df.isnull().sum()
display(
    missing[missing > 0].sort_values(ascending=False)
)

Outdoor_link_irradiance_data                                      42443
JV_link_raw_data                                                  42443
Add_lay_front_storage_relative_humidity                           42443
Add_lay_front_deposition_synthesis_atmosphere_pressure_partial    42443
Stability_lifetime_energy_yield                                   42443
                                                                  ...
Perovskite_composition_b_ions                                         5
Perovskite_composition_c_ions                                         5
Perovskite_deposition_substrate_temperature                           3
HTL_deposition_substrate_temperature                                  3
Backcontact_deposition_thermal_annealing_temperature                  3
Length: 222, dtype: int64

In [8]:
df_clean = df.dropna(axis=1, how="all")
print("Original dimensions:", df.shape)
print("New dimensions:", df_clean.shape)
print("Columns removed:", df.shape[1]-df_clean.shape[1])

Original dimensions: (42443, 410)
New dimensions: (42443, 370)
Columns removed: 40

In [9]:
print(df.isna().all().sum())

40

In [29]:
keywords = [
    "Perovskite_composition",
    "bandgap",
    "band_gap",
    "JV_",
    "ETL",
    "HTL",
    "Substrate",
    "Backcontact",
    "Cell_architecture"
]
relevant_col = [
    col for col in df_clean.columns
    if any(word.lower() in col.lower() for word in keywords)
]
print(relevant_col)

['Cell_number_of_cells_per_substrate', 'Cell_architecture', 'Module_JV_data_recalculated_per_cell', 'Substrate_stack_sequence', 'Substrate_thickness', 'Substrate_area', 'Substrate_supplier', 'Substrate_brand_name', 'Substrate_deposition_procedure', 'Substrate_etching_procedure', 'Substrate_cleaning_procedure', 'ETL_stack_sequence', 'ETL_thickness', 'ETL_additives_compounds', 'ETL_additives_concentrations', 'ETL_deposition_procedure', 'ETL_deposition_aggregation_state_of_reactants', 'ETL_deposition_synthesis_atmosphere', 'ETL_deposition_synthesis_atmosphere_pressure_total', 'ETL_deposition_synthesis_atmosphere_pressure_partial', 'ETL_deposition_synthesis_atmosphere_relative_humidity', 'ETL_deposition_solvents', 'ETL_deposition_solvents_mixing_ratios', 'ETL_deposition_solvents_supplier', 'ETL_deposition_solvents_purity', 'ETL_deposition_reaction_solutions_compounds', 'ETL_deposition_reaction_solutions_compounds_supplier', 'ETL_deposition_reaction_solutions_compounds_purity', 'ETL_deposition_reaction_solutions_concentrations', 'ETL_deposition_reaction_solutions_volumes', 'ETL_deposition_reaction_solutions_age', 'ETL_deposition_reaction_solutions_temperature', 'ETL_deposition_substrate_temperature', 'ETL_deposition_thermal_annealing_temperature', 'ETL_deposition_thermal_annealing_time', 'ETL_deposition_thermal_annealing_atmosphere', 'ETL_storage_time_until_next_deposition_step', 'ETL_storage_atmosphere', 'ETL_storage_relative_humidity', 'ETL_surface_treatment_before_next_deposition_step', 'Perovskite_composition_perovskite_ABC3_structure', 'Perovskite_composition_perovskite_inspired_structure', 'Perovskite_composition_a_ions', 'Perovskite_composition_a_ions_coefficients', 'Perovskite_composition_b_ions', 'Perovskite_composition_b_ions_coefficients', 'Perovskite_composition_c_ions', 'Perovskite_composition_c_ions_coefficients', 'Perovskite_composition_none_stoichiometry_components_in_excess', 'Perovskite_composition_short_form', 'Perovskite_composition_long_form', 'Perovskite_composition_assumption', 'Perovskite_composition_inorganic', 'Perovskite_composition_leadfree', 'Perovskite_band_gap', 'Perovskite_band_gap_graded', 'Perovskite_band_gap_estimation_basis', 'Perovskite_deposition_substrate_temperature', 'HTL_stack_sequence', 'HTL_thickness_list', 'HTL_additives_compounds', 'HTL_additives_concentrations', 'HTL_deposition_procedure', 'HTL_deposition_aggregation_state_of_reactants', 'HTL_deposition_synthesis_atmosphere', 'HTL_deposition_synthesis_atmosphere_pressure_total', 'HTL_deposition_synthesis_atmosphere_pressure_partial', 'HTL_deposition_synthesis_atmosphere_relative_humidity', 'HTL_deposition_solvents', 'HTL_deposition_solvents_mixing_ratios', 'HTL_deposition_solvents_supplier', 'HTL_deposition_solvents_purity', 'HTL_deposition_reaction_solutions_compounds', 'HTL_deposition_reaction_solutions_compounds_supplier', 'HTL_deposition_reaction_solutions_compounds_purity', 'HTL_deposition_reaction_solutions_concentrations', 'HTL_deposition_reaction_solutions_volumes', 'HTL_deposition_reaction_solutions_age', 'HTL_deposition_reaction_solutions_temperature', 'HTL_deposition_substrate_temperature', 'HTL_deposition_thermal_annealing_temperature', 'HTL_deposition_thermal_annealing_time', 'HTL_deposition_thermal_annealing_atmosphere', 'HTL_storage_time_until_next_deposition_step', 'HTL_storage_atmosphere', 'HTL_storage_relative_humidity', 'HTL_surface_treatment_before_next_deposition_step', 'Backcontact_stack_sequence', 'Backcontact_thickness_list', 'Backcontact_additives_compounds', 'Backcontact_additives_concentrations', 'Backcontact_deposition_procedure', 'Backcontact_deposition_aggregation_state_of_reactants', 'Backcontact_deposition_synthesis_atmosphere', 'Backcontact_deposition_synthesis_atmosphere_pressure_total', 'Backcontact_deposition_synthesis_atmosphere_pressure_partial', 'Backcontact_deposition_synthesis_atmosphere_relative_humidity', 'Backcontact_deposition_solvents', 'Backcontact_deposition_solvents_mixing_ratios', 'Backcontact_deposition_solvents_supplier', 'Backcontact_deposition_solvents_purity', 'Backcontact_deposition_reaction_solutions_compounds', 'Backcontact_deposition_reaction_solutions_compounds_supplier', 'Backcontact_deposition_reaction_solutions_compounds_purity', 'Backcontact_deposition_reaction_solutions_concentrations', 'Backcontact_deposition_reaction_solutions_volumes', 'Backcontact_deposition_reaction_solutions_age', 'Backcontact_deposition_reaction_solutions_temperature', 'Backcontact_deposition_substrate_temperature', 'Backcontact_deposition_thermal_annealing_temperature', 'Backcontact_deposition_thermal_annealing_time', 'Backcontact_deposition_thermal_annealing_atmosphere', 'Backcontact_storage_time_until_next_deposition_step', 'Backcontact_storage_atmosphere', 'Backcontact_storage_relative_humidity', 'Backcontact_surface_treatment_before_next_deposition_step', 'Add_lay_front_deposition_substrate_temperature', 'Add_lay_back_deposition_substrate_temperature', 'JV_measured', 'JV_average_over_n_number_of_cells', 'JV_certified_values', 'JV_certification_institute', 'JV_storage_age_of_cell', 'JV_storage_atmosphere', 'JV_storage_relative_humidity', 'JV_test_atmosphere', 'JV_test_relative_humidity', 'JV_test_temperature', 'JV_light_source_type', 'JV_light_source_brand_name', 'JV_light_source_simulator_class', 'JV_light_intensity', 'JV_light_spectra', 'JV_light_wavelength_range', 'JV_light_illumination_direction', 'JV_light_masked_cell', 'JV_light_mask_area', 'JV_scan_speed', 'JV_scan_delay_time', 'JV_scan_integration_time', 'JV_scan_voltage_step', 'JV_preconditioning_protocol', 'JV_preconditioning_time', 'JV_preconditioning_potential', 'JV_preconditioning_light_intensity', 'JV_reverse_scan_Voc', 'JV_reverse_scan_Jsc', 'JV_reverse_scan_FF', 'JV_reverse_scan_PCE', 'JV_reverse_scan_Vmp', 'JV_reverse_scan_Jmp', 'JV_reverse_scan_series_resistance', 'JV_reverse_scan_shunt_resistance', 'JV_forward_scan_Voc', 'JV_forward_scan_Jsc', 'JV_forward_scan_FF', 'JV_forward_scan_PCE', 'JV_forward_scan_Vmp', 'JV_forward_scan_Jmp', 'JV_forward_scan_series_resistance', 'JV_forward_scan_shunt_resistance', 'JV_default_Voc', 'JV_default_Jsc', 'JV_default_FF', 'JV_default_PCE', 'JV_default_Voc_scan_direction', 'JV_default_Jsc_scan_direction', 'JV_default_FF_scan_direction', 'JV_default_PCE_scan_direction', 'JV_hysteresis_index', 'Stability_periodic_JV_measurements', 'Stability_periodic_JV_measurements_time_between_jv', 'Outdoor_periodic_JV_measurements']

In [31]:

summary = pd.DataFrame({
    "available": df_clean[relevant_col].notna().sum(),
    "missing" : df_clean[relevant_col].isna().sum()
})
summary["missing %"] = (summary["missing"]/len(df_clean)*100)
display(summary)

,available,missing,missing %
Cell_number_of_cells_per_substrate,42443,0,0.000000
Cell_architecture,42443,0,0.000000
Module_JV_data_recalculated_per_cell,42443,0,0.000000
Substrate_stack_sequence,42443,0,0.000000
Substrate_thickness,346,42097,99.184789
...,...,...,...
JV_default_PCE_scan_direction,41519,924,2.177037
JV_hysteresis_index,7877,34566,81.440991
Stability_periodic_JV_measurements,42443,0,0.000000
Stability_periodic_JV_measurements_time_between_jv,42443,0,0.000000
Outdoor_periodic_JV_measurements,42443,0,0.000000